# Generated by Django 4.1.7 on 2023-03-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0006_alter_orderdetail_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
